# Generated by Django 3.2.8 on 2022-01-03 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tdata_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 3, 10, 4, 51, 492246, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
